name: fastapi-drive

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:?}
      S3_SECRET_KEY: ${S3_SECRET_KEY:?}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:?}
      S3_BUCKET_URL: ${S3_BUCKET_URL:?}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:?}
